### ISSUE TITLE
Crash when classloading agency.highlysuspect.rhododendrite.block.DirectionalBlockButBetter

### ISSUE THREAD

**Issue by jaz3001** [quat1024/incorporeal-2-forge#11]
Description:
Crashes when attempting to load a world when installed alongside Apotheosis.

Crash Log: 
[crash-2021-08-20_13.20.17-client.txt](https://github.com/quat1024/incorporeal-2-forge/files/7023163/crash-2021-08-20_13.20.17-client.txt)

**Comment by quat1024** [comment]
Turns out this isn't really Apotheosis but it's "whoever classloads that method"; placing one of the rotatable blocks from Rhododendrite with right-click does the same thing

**Comment by quat1024** [comment]
Fix scheduled for 0.9.1, find a build on my Actions https://github.com/quat1024/incorporeal-2-forge/actions/runs/1152629942 or on Modrinth here https://modrinth.com/mod/incorporeal-2-rhododendrite/version/mMvQIG3r in a little bit
